POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Prakriti",
    "email": "prakriti2@gmail.com",
    "password": "aaaaaa"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{  
    "email": "prakriti2@gmail.com",
    "password": "aaaaaa"
}
